### ISSUE TITLE
The client role should be able to configure shell

### ISSUE THREAD

**Issue by tcarrondo** [wzzrd/ansible-collection-atuin#2]
With something like:
```
    - name: Enable Atuin
      lineinfile:
        dest: "/home/{{ user }} /.zshrc"
        state: "present"
        line: 'eval "$(atuin init zsh)"'
```
